version: '3'
services:
    liferay: 
      image: liferay/portal:7.2.0-ga1
      #image: liferay/dxp:7.2.10
      environment:
        - LIFERAY_TERMS_PERIOD_OF_PERIOD_USE_PERIOD_REQUIRED=false
        - LIFERAY_PASSWORDS_PERIOD_DEFAULT_PERIOD_POLICY_PERIOD_CHANGE_PERIOD_REQUIRED=false
        - LIFERAY_USERS_PERIOD_REMINDER_PERIOD_QUERIES_PERIOD_ENABLED=false
        - LIFERAY_USERS_PERIOD_REMINDER_PERIOD_QUERIES_PERIOD_REQUIRED=false
        - LIFERAY_USERS_PERIOD_REMINDER_PERIOD_QUERIES_PERIOD_CUSTOM_PERIOD_QUESTION_PERIOD_ENABLED=false
        - LIFERAY_SETUP_PERIOD_WIZARD_PERIOD_ENABLED=false
      ports:
        - 8080:8080
      volumes:
        - ./deploy:/etc/liferay/mount/deploy



